version: '3.8'

services:
  webrtc-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webrtc-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000 # Explicitly define the port for consistency
    restart: unless-stopped
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: